baseurl = "https://www.pengjielee.cn"
title = "Pengjielee's blog"
paginate = "10" # Number of posts per page
theme = "simple"
publishDir = 'dist'

[Params]
  subtitle = "真正的优秀不是优于别人，而是优于过去的自己。" # Logo subtitle
  keywords = "pengjielee,个人博客"
  description = "Pengjielee的个人博客" # Description of your site
  mainSections = ["post", "blog", "docs"]
  dateformat = "2006-01-02"
  #googleFontsLink = "https://fonts.googleapis.com/css?family=Ubuntu"



